export const ErrorCodes = {
  MANIFEST_INVALID: 'MANIFEST_INVALID',
  WORKFLOW_INVALID: 'WORKFLOW_INVALID',
  PACKAGE_NOT_FOUND: 'PACKAGE_NOT_FOUND',
  BACKEND_UNAVAILABLE: 'BACKEND_UNAVAILABLE',
  POLICY_DENIED: 'POLICY_DENIED',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  APPROVAL_TIMEOUT: 'APPROVAL_TIMEOUT',
  RUN_NOT_FOUND: 'RUN_NOT_FOUND',
  RUN_ALREADY_FINISHED: 'RUN_ALREADY_FINISHED',
  RUN_ALREADY_COMPLETED: 'RUN_ALREADY_COMPLETED',
  INPUT_INVALID: 'INPUT_INVALID',
  ADAPTER_PROTOCOL_ERROR: 'ADAPTER_PROTOCOL_ERROR',
  OUTPUT_SCHEMA_INVALID: 'OUTPUT_SCHEMA_INVALID',
  SIGNATURE_INVALID: 'SIGNATURE_INVALID',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export class SpwnrError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly details?: unknown,
  ) {
    super(message);
    this.name = 'SpwnrError';
  }
}
